version: "3.8"
services:
  database:
    container_name: database
    build: ./database
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./database/mongo/data:/data/db #Helps to store MongoDB data in `./mongo/data`

  backend:
    container_name: backend
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventDB
    ports:
      - "3001:3001"
    depends_on:
      - database

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
