# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production
RUN npm install -g typescript

# Copy the rest of your application's code
COPY . .

# transpile TS -> JS
RUN tsc

# Your app binds to port 3001
EXPOSE 3001

# Define the command to run your app using CMD which defines your runtime
CMD ["node", "dist/server.js"]
