/* tslint:disable */
/* eslint-disable */
/**
 * Event API
 * API to manage event data for the Event Crowdsource application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventCategory = {
    Music: 'Music',
    Conference: 'Conference',
    Workshop: 'Workshop',
    Sports: 'Sports',
    Festival: 'Festival'
} as const;
export type EventCategory = typeof EventCategory[keyof typeof EventCategory];


export function instanceOfEventCategory(value: any): boolean {
    return Object.values(EventCategory).includes(value);
}

export function EventCategoryFromJSON(json: any): EventCategory {
    return EventCategoryFromJSONTyped(json, false);
}

export function EventCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCategory {
    return json as EventCategory;
}

export function EventCategoryToJSON(value?: EventCategory | null): any {
    return value as any;
}

