/* tslint:disable */
/* eslint-disable */
/**
 * Event API
 * API to manage event data for the Event Crowdsource application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    rating?: string;
}

/**
 * Check if a given object implements the Host interface.
 */
export function instanceOfHost(value: object): boolean {
    return true;
}

export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function HostToJSON(value?: Host | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'rating': value['rating'],
    };
}

