/* tslint:disable */
/* eslint-disable */
/**
 * Event API
 * API to manage event data for the Event Crowdsource application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * Indicates whether the payment was successful
     * @type {boolean}
     * @memberof PaymentResponse
     */
    success?: boolean;
    /**
     * A message detailing the payment outcome
     * @type {string}
     * @memberof PaymentResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): boolean {
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PaymentResponseToJSON(value?: PaymentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

