/* tslint:disable */
/* eslint-disable */
/**
 * Event API
 * API to manage event data for the Event Crowdsource application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequest
 */
export interface PaymentRequest {
    /**
     * Payment amount in cents
     * @type {number}
     * @memberof PaymentRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the PaymentRequest interface.
 */
export function instanceOfPaymentRequest(value: object): boolean {
    return true;
}

export function PaymentRequestFromJSON(json: any): PaymentRequest {
    return PaymentRequestFromJSONTyped(json, false);
}

export function PaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function PaymentRequestToJSON(value?: PaymentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
    };
}

